
# fml_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'bofx eofx newline tab interpolant lce rce string\n\tstart \t: \tbofx\n\t\t\t|\tstart eofx\n\t\t\t|\tstart code\n\t\n\tcode \t: \tnewline \n\t\n\tcode \t: \ttab\n\t\n\tcode \t: \tstring\n\t\n\tcode \t: \tlce\n\t\n\tcode \t: \trce\n\t\n\tcode \t: \tinterpolant\n\t'
    
_lr_action_items = {'bofx':([0,],[1,]),'$end':([1,2,3,4,5,6,7,8,9,10,],[-1,0,-9,-6,-2,-7,-3,-8,-5,-4,]),'interpolant':([1,2,3,4,5,6,7,8,9,10,],[-1,3,-9,-6,-2,-7,-3,-8,-5,-4,]),'tab':([1,2,3,4,5,6,7,8,9,10,],[-1,9,-9,-6,-2,-7,-3,-8,-5,-4,]),'lce':([1,2,3,4,5,6,7,8,9,10,],[-1,6,-9,-6,-2,-7,-3,-8,-5,-4,]),'string':([1,2,3,4,5,6,7,8,9,10,],[-1,4,-9,-6,-2,-7,-3,-8,-5,-4,]),'rce':([1,2,3,4,5,6,7,8,9,10,],[-1,8,-9,-6,-2,-7,-3,-8,-5,-4,]),'eofx':([1,2,3,4,5,6,7,8,9,10,],[-1,5,-9,-6,-2,-7,-3,-8,-5,-4,]),'newline':([1,2,3,4,5,6,7,8,9,10,],[-1,10,-9,-6,-2,-7,-3,-8,-5,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[2,]),'code':([2,],[7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> bofx','start',1,'p_bofx','fml_yacc.py',7),
  ('start -> start eofx','start',2,'p_bofx','fml_yacc.py',8),
  ('start -> start code','start',2,'p_bofx','fml_yacc.py',9),
  ('code -> newline','code',1,'p_newline','fml_yacc.py',15),
  ('code -> tab','code',1,'p_tab','fml_yacc.py',22),
  ('code -> string','code',1,'p_string','fml_yacc.py',29),
  ('code -> lce','code',1,'p_lce','fml_yacc.py',36),
  ('code -> rce','code',1,'p_rce','fml_yacc.py',43),
  ('code -> interpolant','code',1,'p_interpolant','fml_yacc.py',50),
]
