s = """
o mttc.random.random 13
c mttc.random.random 13
o mttc.random.random 17
c mttc.random.random 17
o mttc.random.random 32
c mttc.random.random 32
o mttc.random.random 38
c mttc.random.random 38
o mttc.random.random 39
c mttc.random.random 39
o mttc.random.random 45
o mttc.random.random 46
c mttc.random.random 46
c mttc.random.random 45
o mttc.random.random 52
o mttc.random.random 53
c mttc.random.random 53
o mttc.random.random 54
c mttc.random.random 54
o mttc.random.random 55
c mttc.random.random 55
o mttc.random.random 56
c mttc.random.random 56
c mttc.random.random 52
o mttc.random.random 65
c mttc.random.random 65
o mttc.random.random 72
c mttc.random.random 72
o mttc.random.random 78
c mttc.random.random 78
o mttc.random.random 79
c mttc.random.random 79
o mttc.random.random 86
o mttc.random.random 87
c mttc.random.random 87
c mttc.random.random 86
o mttc.random.random 104
c mttc.random.random 104
o mttc.random.random 115
c mttc.random.random 115
o mttc.random.random 117
c mttc.random.random 117
o mttc.random.random 131
c mttc.random.random 131
o mttc.random.random 138
o mttc.random.random 144
c mttc.random.random 144
c mttc.random.random 138
o mttc.random.random 160
c mttc.random.random 160
o mttc.random.random 161
c mttc.random.random 161
o mttc.random.random 162
c mttc.random.random 162
o mttc.random.random 164
c mttc.random.random 164
o mttc.random.random 166
c mttc.random.random 166
o mttc.random.random 167
o mttc.random.random 168
c mttc.random.random 168
c mttc.random.random 167
o mttc.random.random 175
o mttc.random.random 182
c mttc.random.random 182
c mttc.random.random 175
o mttc.vopp.rw.fy.brownian 11
c mttc.vopp.rw.fy.brownian 11
o mttc.vopp.rw.fy.brownian 13
c mttc.vopp.rw.fy.brownian 13
o mttc.vopp.rw.fy.vasicek_step 5
c mttc.vopp.rw.fy.vasicek_step 5
o mttc.vopp.rw.fy.bs_step 5
c mttc.vopp.rw.fy.bs_step 5
o mttc.vopp.rw.fy.heston_step 5
c mttc.vopp.rw.fy.heston_step 5
o mttc.vopp.rw.fy.heston_vol_step 5
c mttc.vopp.rw.fy.heston_vol_step 5
o mttc.vopp.rw.fy.heston_vol_step 7
c mttc.vopp.rw.fy.heston_vol_step 7
o mttc.vopp.rw.fy.heston_vol_step 9
c mttc.vopp.rw.fy.heston_vol_step 9
o mttc.vopp.rw.fy.heston_vol_step 11
c mttc.vopp.rw.fy.heston_vol_step 11
o mttc.vopp.rw.fy.cumprod 5
o mttc.vopp.rw.fy.cumprod 6
c mttc.vopp.rw.fy.cumprod 6
c mttc.vopp.rw.fy.cumprod 5
o mttc.vopp.rw.fy.option_sim_stock_return 13
c mttc.vopp.rw.fy.option_sim_stock_return 13
o mttc.vopp.rw.fy.option_sim_stock_return 14
c mttc.vopp.rw.fy.option_sim_stock_return 14
o mttc.vopp.rw.fy.option_sim_stock_return 15
c mttc.vopp.rw.fy.option_sim_stock_return 15
o mttc.vopp.rw.fy.option_sim_stock_return 16
c mttc.vopp.rw.fy.option_sim_stock_return 16
o mttc.vopp.rw.fy.option_sim_stock_return 18
c mttc.vopp.rw.fy.option_sim_stock_return 18
o mttc.vopp.rw.fy.option_sim_stock_return 21
c mttc.vopp.rw.fy.option_sim_stock_return 21
o mttc.vopp.rw.fy.option_sim_stock_return 23
c mttc.vopp.rw.fy.option_sim_stock_return 23
o mttc.vopp.rw.fy.option_sim_stock_return 25
c mttc.vopp.rw.fy.option_sim_stock_return 25
o mttc.vopp.rw.fy.option_sim_stock_return 26
c mttc.vopp.rw.fy.option_sim_stock_return 26
o mttc.vopp.rw.fy.option_sim_stock_return 28
o mttc.vopp.rw.fy.option_sim_stock_return 29
c mttc.vopp.rw.fy.option_sim_stock_return 29
o mttc.vopp.rw.fy.option_sim_stock_return 31
c mttc.vopp.rw.fy.option_sim_stock_return 31
o mttc.vopp.rw.fy.option_sim_stock_return 33
c mttc.vopp.rw.fy.option_sim_stock_return 33
o mttc.vopp.rw.fy.option_sim_stock_return 34
c mttc.vopp.rw.fy.option_sim_stock_return 34
c mttc.vopp.rw.fy.option_sim_stock_return 28
o mttc.vopp.rw.fy.option_sim_stock_return 36
c mttc.vopp.rw.fy.option_sim_stock_return 36
o mttc.vopp.rw.fy.option_sim_stock_return 37
c mttc.vopp.rw.fy.option_sim_stock_return 37
o mttc.vopp.rw.fy.option_sim_stock_return 40
o mttc.vopp.rw.fy.option_sim_stock_return 41
c mttc.vopp.rw.fy.option_sim_stock_return 41
o mttc.vopp.rw.fy.option_sim_stock_return 42
c mttc.vopp.rw.fy.option_sim_stock_return 42
o mttc.vopp.rw.fy.option_sim_stock_return 43
c mttc.vopp.rw.fy.option_sim_stock_return 43
o mttc.vopp.rw.fy.option_sim_stock_return 44
c mttc.vopp.rw.fy.option_sim_stock_return 44
c mttc.vopp.rw.fy.option_sim_stock_return 40
o mttc.vopp.rw.fy.option_sim_stock_return 47
o mttc.vopp.rw.fy.option_sim_stock_return 48
c mttc.vopp.rw.fy.option_sim_stock_return 48
c mttc.vopp.rw.fy.option_sim_stock_return 47
o mttc.vopp.rw.fy.pv_t_payoff 6
c mttc.vopp.rw.fy.pv_t_payoff 6
o mttc.vopp.rw.fy.pv_t_payoff 7
o mttc.vopp.rw.fy.pv_t_payoff 8
c mttc.vopp.rw.fy.pv_t_payoff 8
o mttc.vopp.rw.fy.pv_t_payoff 10
c mttc.vopp.rw.fy.pv_t_payoff 10
o mttc.vopp.rw.fy.pv_t_payoff 12
c mttc.vopp.rw.fy.pv_t_payoff 12
o mttc.vopp.rw.fy.pv_t_payoff 14
c mttc.vopp.rw.fy.pv_t_payoff 14
o mttc.vopp.rw.fy.pv_t_payoff 15
c mttc.vopp.rw.fy.pv_t_payoff 15
c mttc.vopp.rw.fy.pv_t_payoff 7
o mttc.vopp.rw.fy.pv_t_payoff 17
c mttc.vopp.rw.fy.pv_t_payoff 17
o mttc.vopp.rw.fy.option_pv_force_payoff 7
c mttc.vopp.rw.fy.option_pv_force_payoff 7
o mttc.vopp.rw.fy.option_pv_force_payoff 9
c mttc.vopp.rw.fy.option_pv_force_payoff 9
o mttc.vopp.rw.fy.option_pv_force_payoff 13
c mttc.vopp.rw.fy.option_pv_force_payoff 13
o mttc.vopp.rw.fy.option_pv_zero_payoff 7
c mttc.vopp.rw.fy.option_pv_zero_payoff 7
o mttc.algo.fy.spec 440
c mttc.algo.fy.spec 440
o mttc.algo.fy.spec 441
c mttc.algo.fy.spec 441
o mttc.algo.fy.spec 453
c mttc.algo.fy.spec 453
o mttc.algo.fy.spec 454
c mttc.algo.fy.spec 454
o mttc.algo.fy.init_vars 6
c mttc.algo.fy.init_vars 6
o mttc.algo.fy.init_vars 8
c mttc.algo.fy.init_vars 8
o mttc.algo.fy.init_vars 10
o mttc.algo.fy.init_vars 11
c mttc.algo.fy.init_vars 11
o mttc.algo.fy.init_vars 13
c mttc.algo.fy.init_vars 13
c mttc.algo.fy.init_vars 10
o mttc.algo.fy.init_decision_hash_key 11
c mttc.algo.fy.init_decision_hash_key 11
o mttc.algo.fy.init_steps 6
o mttc.algo.fy.init_steps 9
c mttc.algo.fy.init_steps 9
c mttc.algo.fy.init_steps 6
o mttc.hilbert.fy.coord_to_hilbert 4
c mttc.hilbert.fy.coord_to_hilbert 4
o mttc.hilbert.fy.coord_to_hilbert 5
c mttc.hilbert.fy.coord_to_hilbert 5
o mttc.hilbert.fy.coord_to_hilbert 7
c mttc.hilbert.fy.coord_to_hilbert 7
o mttc.hilbert.fy.coord_to_hilbert 11
c mttc.hilbert.fy.coord_to_hilbert 11
o mttc.hilbert.fy.coord_to_hilbert 12
o mttc.hilbert.fy.coord_to_hilbert 13
c mttc.hilbert.fy.coord_to_hilbert 13
o mttc.hilbert.fy.coord_to_hilbert 14
o mttc.hilbert.fy.coord_to_hilbert 16
o mttc.hilbert.fy.coord_to_hilbert 17
c mttc.hilbert.fy.coord_to_hilbert 17
o mttc.hilbert.fy.coord_to_hilbert 20
c mttc.hilbert.fy.coord_to_hilbert 20
o mttc.hilbert.fy.coord_to_hilbert 21
c mttc.hilbert.fy.coord_to_hilbert 21
o mttc.hilbert.fy.coord_to_hilbert 22
c mttc.hilbert.fy.coord_to_hilbert 22
c mttc.hilbert.fy.coord_to_hilbert 19
c mttc.hilbert.fy.coord_to_hilbert 14
o mttc.hilbert.fy.coord_to_hilbert 25
c mttc.hilbert.fy.coord_to_hilbert 25
c mttc.hilbert.fy.coord_to_hilbert 12
o mttc.hilbert.fy.coord_to_hilbert 28
o mttc.hilbert.fy.coord_to_hilbert 29
c mttc.hilbert.fy.coord_to_hilbert 29
c mttc.hilbert.fy.coord_to_hilbert 28
o mttc.hilbert.fy.coord_to_hilbert 32
c mttc.hilbert.fy.coord_to_hilbert 32
o mttc.hilbert.fy.coord_to_hilbert 34
c mttc.hilbert.fy.coord_to_hilbert 34
o mttc.hilbert.fy.coord_to_hilbert 35
o mttc.hilbert.fy.coord_to_hilbert 36
o mttc.hilbert.fy.coord_to_hilbert 37
c mttc.hilbert.fy.coord_to_hilbert 37
c mttc.hilbert.fy.coord_to_hilbert 36
o mttc.hilbert.fy.coord_to_hilbert 38
c mttc.hilbert.fy.coord_to_hilbert 38
c mttc.hilbert.fy.coord_to_hilbert 35
o mttc.hilbert.fy.coord_to_hilbert 40
o mttc.hilbert.fy.coord_to_hilbert 41
c mttc.hilbert.fy.coord_to_hilbert 41
c mttc.hilbert.fy.coord_to_hilbert 40
o mttc.hilbert.fy.coord_to_hilbert 45
c mttc.hilbert.fy.coord_to_hilbert 45
o mttc.hilbert.fy.coord_to_hilbert 47
c mttc.hilbert.fy.coord_to_hilbert 47
o mttc.hilbert.fy.coord_to_hilbert 48
c mttc.hilbert.fy.coord_to_hilbert 48
o mttc.hilbert.fy.coord_to_hilbert 51
o mttc.hilbert.fy.coord_to_hilbert 52
o mttc.hilbert.fy.coord_to_hilbert 53
o mttc.hilbert.fy.coord_to_hilbert 54
c mttc.hilbert.fy.coord_to_hilbert 54
c mttc.hilbert.fy.coord_to_hilbert 53
o mttc.hilbert.fy.coord_to_hilbert 57
c mttc.hilbert.fy.coord_to_hilbert 57
o mttc.hilbert.fy.coord_to_hilbert 59
o mttc.hilbert.fy.coord_to_hilbert 60
c mttc.hilbert.fy.coord_to_hilbert 60
o mttc.hilbert.fy.coord_to_hilbert 61
c mttc.hilbert.fy.coord_to_hilbert 61
c mttc.hilbert.fy.coord_to_hilbert 59
c mttc.hilbert.fy.coord_to_hilbert 52
c mttc.hilbert.fy.coord_to_hilbert 51
o mttc.hilbert.fy.hilbert_to_coord 5
c mttc.hilbert.fy.hilbert_to_coord 5
o mttc.hilbert.fy.hilbert_to_coord 7
c mttc.hilbert.fy.hilbert_to_coord 7
o mttc.hilbert.fy.hilbert_to_coord 8
c mttc.hilbert.fy.hilbert_to_coord 8
o mttc.hilbert.fy.hilbert_to_coord 10
o mttc.hilbert.fy.hilbert_to_coord 11
o mttc.hilbert.fy.hilbert_to_coord 12
o mttc.hilbert.fy.hilbert_to_coord 13
c mttc.hilbert.fy.hilbert_to_coord 13
c mttc.hilbert.fy.hilbert_to_coord 12
o mttc.hilbert.fy.hilbert_to_coord 17
c mttc.hilbert.fy.hilbert_to_coord 17
o mttc.hilbert.fy.hilbert_to_coord 19
o mttc.hilbert.fy.hilbert_to_coord 20
c mttc.hilbert.fy.hilbert_to_coord 20
o mttc.hilbert.fy.hilbert_to_coord 21
c mttc.hilbert.fy.hilbert_to_coord 21
c mttc.hilbert.fy.hilbert_to_coord 19
c mttc.hilbert.fy.hilbert_to_coord 11
c mttc.hilbert.fy.hilbert_to_coord 10
o mttc.hilbert.fy.hilbert_to_coord 26
c mttc.hilbert.fy.hilbert_to_coord 26
o mttc.hilbert.fy.hilbert_to_coord 31
c mttc.hilbert.fy.hilbert_to_coord 31
o mttc.hilbert.fy.hilbert_to_coord 35
o mttc.hilbert.fy.hilbert_to_coord 36
c mttc.hilbert.fy.hilbert_to_coord 36
c mttc.hilbert.fy.hilbert_to_coord 35
o mttc.hilbert.fy.hilbert_to_coord 39
c mttc.hilbert.fy.hilbert_to_coord 39
o mttc.hilbert.fy.hilbert_to_coord 43
c mttc.hilbert.fy.hilbert_to_coord 43
o mttc.hilbert.fy.hilbert_to_coord 44
o mttc.hilbert.fy.hilbert_to_coord 45
c mttc.hilbert.fy.hilbert_to_coord 45
o mttc.hilbert.fy.hilbert_to_coord 47
o mttc.hilbert.fy.hilbert_to_coord 48
o mttc.hilbert.fy.hilbert_to_coord 49
c mttc.hilbert.fy.hilbert_to_coord 49
o mttc.hilbert.fy.hilbert_to_coord 53
c mttc.hilbert.fy.hilbert_to_coord 53
o mttc.hilbert.fy.hilbert_to_coord 54
c mttc.hilbert.fy.hilbert_to_coord 54
o mttc.hilbert.fy.hilbert_to_coord 55
c mttc.hilbert.fy.hilbert_to_coord 55
c mttc.hilbert.fy.hilbert_to_coord 52
c mttc.hilbert.fy.hilbert_to_coord 47
o mttc.hilbert.fy.hilbert_to_coord 58
c mttc.hilbert.fy.hilbert_to_coord 58
c mttc.hilbert.fy.hilbert_to_coord 44
o mttc.hilbert.fy.hilbert_to_coord 61
c mttc.hilbert.fy.hilbert_to_coord 61
o mttc.hilbert.fy.hilbert_to_coord 62
c mttc.hilbert.fy.hilbert_to_coord 62
o mttc.hilbert.fy.hilbert_to_coord 63
c mttc.hilbert.fy.hilbert_to_coord 63
o mttc.hilbert.fy.hilbert_less_than 4
c mttc.hilbert.fy.hilbert_less_than 4
o mttc.hilbert.fy.hilbert_less_than 5
o mttc.hilbert.fy.hilbert_less_than 6
o mttc.hilbert.fy.hilbert_less_than 7
c mttc.hilbert.fy.hilbert_less_than 7
c mttc.hilbert.fy.hilbert_less_than 10
c mttc.hilbert.fy.hilbert_less_than 5
o mttc.hilbert.fy.hilbert_less_than_sub 5
c mttc.hilbert.fy.hilbert_less_than_sub 5
o mttc.hilbert.fy.hilbert_argsort_worker 5
c mttc.hilbert.fy.hilbert_argsort_worker 5
o mttc.hilbert.fy.hilbert_argsort_worker 8
c mttc.hilbert.fy.hilbert_argsort_worker 8
o mttc.hilbert.fy.hilbert_argsort_worker 9
c mttc.hilbert.fy.hilbert_argsort_worker 9
o mttc.hilbert.fy.hilbert_argsort_worker 10
c mttc.hilbert.fy.hilbert_argsort_worker 10
o mttc.hilbert.fy.hilbert_argsort_worker 12
o mttc.hilbert.fy.hilbert_argsort_worker 16
o mttc.hilbert.fy.hilbert_argsort_worker 17
c mttc.hilbert.fy.hilbert_argsort_worker 17
c mttc.hilbert.fy.hilbert_argsort_worker 16
o mttc.hilbert.fy.hilbert_argsort_worker 22
o mttc.hilbert.fy.hilbert_argsort_worker 23
c mttc.hilbert.fy.hilbert_argsort_worker 23
c mttc.hilbert.fy.hilbert_argsort_worker 22
o mttc.hilbert.fy.hilbert_argsort_worker 25
o mttc.hilbert.fy.hilbert_argsort_worker 26
c mttc.hilbert.fy.hilbert_argsort_worker 26
c mttc.hilbert.fy.hilbert_argsort_worker 25
o mttc.hilbert.fy.hilbert_argsort_worker 28
c mttc.hilbert.fy.hilbert_argsort_worker 28
o mttc.hilbert.fy.hilbert_argsort_worker 29
c mttc.hilbert.fy.hilbert_argsort_worker 29
o mttc.hilbert.fy.hilbert_argsort_worker 30
c mttc.hilbert.fy.hilbert_argsort_worker 30
o mttc.hilbert.fy.hilbert_argsort_worker 32
c mttc.hilbert.fy.hilbert_argsort_worker 32
o mttc.hilbert.fy.hilbert_argsort_worker 33
c mttc.hilbert.fy.hilbert_argsort_worker 33
c mttc.hilbert.fy.hilbert_argsort_worker 12
o mttc.hilbert.fy.hilbert_argsort_worker 35
o mttc.hilbert.fy.hilbert_argsort_worker 36
c mttc.hilbert.fy.hilbert_argsort_worker 36
c mttc.hilbert.fy.hilbert_argsort_worker 35
o mttc.hilbert.fy.hilbert_argsort_worker 41
c mttc.hilbert.fy.hilbert_argsort_worker 41
o mttc.hilbert.fy.hilbert_argsort_worker 46
c mttc.hilbert.fy.hilbert_argsort_worker 46
o mttc.hilbert.fy.hilbert_argsort 5
o mttc.hilbert.fy.hilbert_argsort 6
c mttc.hilbert.fy.hilbert_argsort 6
c mttc.hilbert.fy.hilbert_argsort 5
o mttc.hilbert.fy.hilbert_argsort 11
c mttc.hilbert.fy.hilbert_argsort 11
o mttc.hilbert.fy.hilbert_nearest 6
o mttc.hilbert.fy.hilbert_nearest 8
c mttc.hilbert.fy.hilbert_nearest 8
o mttc.hilbert.fy.hilbert_nearest 13
c mttc.hilbert.fy.hilbert_nearest 13
c mttc.hilbert.fy.hilbert_nearest 11
o mttc.hilbert.fy.hilbert_nearest 17
c mttc.hilbert.fy.hilbert_nearest 17
o mttc.hilbert.fy.hilbert_nearest 18
c mttc.hilbert.fy.hilbert_nearest 18
o mttc.hilbert.fy.hilbert_nearest 19
o mttc.hilbert.fy.hilbert_nearest 20
c mttc.hilbert.fy.hilbert_nearest 20
o mttc.hilbert.fy.hilbert_nearest 22
o mttc.hilbert.fy.hilbert_nearest 23
c mttc.hilbert.fy.hilbert_nearest 23
o mttc.hilbert.fy.hilbert_nearest 26
c mttc.hilbert.fy.hilbert_nearest 26
c mttc.hilbert.fy.hilbert_nearest 25
c mttc.hilbert.fy.hilbert_nearest 19
o mttc.hilbert.fy.hilbert_nearest 28
c mttc.hilbert.fy.hilbert_nearest 28
o mttc.algo.fy.make_hilbert_steps 7
o mttc.algo.fy.make_hilbert_steps 8
o mttc.algo.fy.make_hilbert_steps 19
c mttc.algo.fy.make_hilbert_steps 19
c mttc.algo.fy.make_hilbert_steps 8
c mttc.algo.fy.make_hilbert_steps 7
o mttc.algo.fy.get_hilbert_order 7
o mttc.algo.fy.get_hilbert_order 15
c mttc.algo.fy.get_hilbert_order 15
c mttc.algo.fy.get_hilbert_order 7
o mttc.algo.fy.get_hilbert_order 17
o mttc.algo.fy.get_hilbert_order 18
c mttc.algo.fy.get_hilbert_order 18
c mttc.algo.fy.get_hilbert_order 17
o mttc.algo.fy.init_height 6
c mttc.algo.fy.init_height 6
o mttc.algo.fy.init_height 7
c mttc.algo.fy.init_height 7
o mttc.algo.fy.init_height 10
o mttc.algo.fy.init_height 11
o mttc.algo.fy.init_height 12
o mttc.algo.fy.init_height 18
c mttc.algo.fy.init_height 18
c mttc.algo.fy.init_height 12
c mttc.algo.fy.init_height 11
c mttc.algo.fy.init_height 10
o mttc.algo.fy.init_pool 5
c mttc.algo.fy.init_pool 5
o mttc.algo.fy.init_pool 7
c mttc.algo.fy.init_pool 7
o mttc.algo.fy.init_pool 9
c mttc.algo.fy.init_pool 9
o mttc.algo.fy.init_pool 10
c mttc.algo.fy.init_pool 10
o mttc.algo.fy.init_pool 12
c mttc.algo.fy.init_pool 12
o mttc.algo.fy.init_sim_price 6
o mttc.algo.fy.init_sim_price 9
c mttc.algo.fy.init_sim_price 9
c mttc.algo.fy.init_sim_price 6
o mttc.algo.fy.get_hilbert_nearest 15
c mttc.algo.fy.get_hilbert_nearest 15
o mttc.algo.fy.get_hilbert_nearest 27
c mttc.algo.fy.get_hilbert_nearest 27
o mttc.algo.fy.get_dist 5
c mttc.algo.fy.get_dist 5
o mttc.algo.fy.get_best_neighbor 6
c mttc.algo.fy.get_best_neighbor 6
o mttc.algo.fy.get_best_neighbor 7
c mttc.algo.fy.get_best_neighbor 7
o mttc.algo.fy.get_best_neighbor 9
c mttc.algo.fy.get_best_neighbor 9
o mttc.algo.fy.get_best_neighbor 10
c mttc.algo.fy.get_best_neighbor 10
o mttc.algo.fy.get_best_neighbor 12
o mttc.algo.fy.get_best_neighbor 13
c mttc.algo.fy.get_best_neighbor 13
o mttc.algo.fy.get_best_neighbor 14
c mttc.algo.fy.get_best_neighbor 14
o mttc.algo.fy.get_best_neighbor 16
o mttc.algo.fy.get_best_neighbor 17
c mttc.algo.fy.get_best_neighbor 17
o mttc.algo.fy.get_best_neighbor 18
c mttc.algo.fy.get_best_neighbor 18
c mttc.algo.fy.get_best_neighbor 16
c mttc.algo.fy.get_best_neighbor 12
o mttc.algo.fy.find_steps 10
o mttc.algo.fy.find_steps 16
c mttc.algo.fy.find_steps 16
c mttc.algo.fy.find_steps 10
o mttc.algo.fy.find_steps 20
o mttc.algo.fy.find_steps 28
c mttc.algo.fy.find_steps 28
c mttc.algo.fy.find_steps 20
o mttc.algo.fy.get_sim_price_step 8
o mttc.algo.fy.get_sim_price_step 12
c mttc.algo.fy.get_sim_price_step 12
c mttc.algo.fy.get_sim_price_step 8
o mttc.algo.fy.get_height 5
o mttc.algo.fy.get_height 6
c mttc.algo.fy.get_height 6
c mttc.algo.fy.get_height 5
o mttc.algo.fy.find_new_candidate 6
c mttc.algo.fy.find_new_candidate 6
o mttc.algo.fy.find_new_candidate 8
o mttc.algo.fy.find_new_candidate 9
c mttc.algo.fy.find_new_candidate 9
o mttc.algo.fy.find_new_candidate 11
o mttc.algo.fy.find_new_candidate 12
o mttc.algo.fy.find_new_candidate 13
c mttc.algo.fy.find_new_candidate 13
o mttc.algo.fy.find_new_candidate 15
c mttc.algo.fy.find_new_candidate 15
o mttc.algo.fy.find_new_candidate 16
c mttc.algo.fy.find_new_candidate 16
o mttc.algo.fy.find_new_candidate 18
o mttc.algo.fy.find_new_candidate 19
c mttc.algo.fy.find_new_candidate 19
o mttc.algo.fy.find_new_candidate 20
c mttc.algo.fy.find_new_candidate 20
o mttc.algo.fy.find_new_candidate 22
c mttc.algo.fy.find_new_candidate 22
o mttc.algo.fy.find_new_candidate 24
c mttc.algo.fy.find_new_candidate 24
c mttc.algo.fy.find_new_candidate 23
c mttc.algo.fy.find_new_candidate 12
c mttc.algo.fy.find_new_candidate 11
o mttc.algo.fy.find_new_candidate 26
o mttc.algo.fy.find_new_candidate 27
c mttc.algo.fy.find_new_candidate 27
c mttc.algo.fy.find_new_candidate 26
c mttc.algo.fy.find_new_candidate 8
o mttc.algo.fy.find_new_candidate 30
c mttc.algo.fy.find_new_candidate 30
o mttc.algo.fy.add_to_empty_pool 6
c mttc.algo.fy.add_to_empty_pool 6
o mttc.algo.fy.add_to_empty_pool 8
c mttc.algo.fy.add_to_empty_pool 8
o mttc.algo.fy.add_to_empty_pool 10
c mttc.algo.fy.add_to_empty_pool 10
o mttc.algo.fy.add_to_empty_pool 12
c mttc.algo.fy.add_to_empty_pool 12
o mttc.algo.fy.add_to_empty_pool 14
c mttc.algo.fy.add_to_empty_pool 14
o mttc.algo.fy.add_to_empty_pool 15
c mttc.algo.fy.add_to_empty_pool 15
o mttc.algo.fy.add_to_empty_pool 17
c mttc.algo.fy.add_to_empty_pool 17
o mttc.algo.fy.update_pool_candidate 4
c mttc.algo.fy.update_pool_candidate 4
o mttc.algo.fy.update_pool_candidate 6
c mttc.algo.fy.update_pool_candidate 6
o mttc.algo.fy.update_pool_candidate 8
c mttc.algo.fy.update_pool_candidate 8
o mttc.algo.fy.update_pool_candidate 10
c mttc.algo.fy.update_pool_candidate 10
o mttc.algo.fy.update_pool_candidate 12
c mttc.algo.fy.update_pool_candidate 12
o mttc.algo.fy.add_new_candidate_to_pool 7
o mttc.algo.fy.add_new_candidate_to_pool 8
c mttc.algo.fy.add_new_candidate_to_pool 8
o mttc.algo.fy.add_new_candidate_to_pool 9
c mttc.algo.fy.add_new_candidate_to_pool 9
o mttc.algo.fy.add_new_candidate_to_pool 12
c mttc.algo.fy.add_new_candidate_to_pool 12
o mttc.algo.fy.add_new_candidate_to_pool 14
c mttc.algo.fy.add_new_candidate_to_pool 14
o mttc.algo.fy.add_new_candidate_to_pool 16
c mttc.algo.fy.add_new_candidate_to_pool 16
o mttc.algo.fy.add_new_candidate_to_pool 17
c mttc.algo.fy.add_new_candidate_to_pool 17
o mttc.algo.fy.add_new_candidate_to_pool 18
c mttc.algo.fy.add_new_candidate_to_pool 18
c mttc.algo.fy.add_new_candidate_to_pool 11
o mttc.algo.fy.add_new_candidate_to_pool 20
c mttc.algo.fy.add_new_candidate_to_pool 20
o mttc.algo.fy.add_new_candidate_to_pool 21
c mttc.algo.fy.add_new_candidate_to_pool 21
o mttc.algo.fy.add_new_candidate_to_pool 31
c mttc.algo.fy.add_new_candidate_to_pool 31
o mttc.algo.fy.crawl_pool 8
c mttc.algo.fy.crawl_pool 8
o mttc.algo.fy.crawl_pool 10
o mttc.algo.fy.crawl_pool 11
o mttc.algo.fy.crawl_pool 12
c mttc.algo.fy.crawl_pool 12
o mttc.algo.fy.crawl_pool 22
c mttc.algo.fy.crawl_pool 22
o mttc.algo.fy.crawl_pool 35
c mttc.algo.fy.crawl_pool 35
c mttc.algo.fy.crawl_pool 24
c mttc.algo.fy.crawl_pool 10
o mttc.algo.fy.crawl_pool 37
o mttc.algo.fy.crawl_pool 38
c mttc.algo.fy.crawl_pool 38
c mttc.algo.fy.crawl_pool 37
o mttc.algo.fy.update_height 6
c mttc.algo.fy.update_height 6
o mttc.algo.fy.update_height 8
c mttc.algo.fy.update_height 8
o mttc.algo.fy.update_height 10
c mttc.algo.fy.update_height 10
o mttc.algo.fy.update_height 12
c mttc.algo.fy.update_height 12
o mttc.algo.fy.cd_trials 10
o mttc.algo.fy.cd_trials 11
c mttc.algo.fy.cd_trials 11
o mttc.algo.fy.cd_trials 13
c mttc.algo.fy.cd_trials 13
o mttc.algo.fy.cd_trials 15
o mttc.algo.fy.cd_trials 16
c mttc.algo.fy.cd_trials 16
o mttc.algo.fy.cd_trials 19
c mttc.algo.fy.cd_trials 19
c mttc.algo.fy.cd_trials 18
c mttc.algo.fy.cd_trials 10
o mttc.algo.fy.cd_trials 21
c mttc.algo.fy.cd_trials 21
o mttc.algo.fy.pv_zero_payoff 7
c mttc.algo.fy.pv_zero_payoff 7
o mttc.algo.fy.pv_zero_payoff 9
c mttc.algo.fy.pv_zero_payoff 9
o mttc.algo.fy.pv_zero_payoff 11
c mttc.algo.fy.pv_zero_payoff 11
o mttc.algo.fy.get_price 7
o mttc.algo.fy.get_price 11
c mttc.algo.fy.get_price 11
c mttc.algo.fy.get_price 7
o mttc.algo.fy.get_price 13
c mttc.algo.fy.get_price 13
o mttc.algo.fy.get_price 14
c mttc.algo.fy.get_price 14
o mttc.algo.fy.update_global_stat 6
c mttc.algo.fy.update_global_stat 6
o mttc.algo.fy.update_global_stat 8
c mttc.algo.fy.update_global_stat 8
o mttc.algo.fy.update_global_stat 10
c mttc.algo.fy.update_global_stat 10
o mttc.algo.fy.get_rdm_decision 7
o mttc.algo.fy.get_rdm_decision 8
o mttc.algo.fy.get_rdm_decision 9
o mttc.algo.fy.get_rdm_decision 15
c mttc.algo.fy.get_rdm_decision 15
c mttc.algo.fy.get_rdm_decision 9
c mttc.algo.fy.get_rdm_decision 8
c mttc.algo.fy.get_rdm_decision 7
o mttc.algo.fy.run_random_walk 12
o mttc.algo.fy.run_random_walk 14
c mttc.algo.fy.run_random_walk 14
o mttc.algo.fy.run_random_walk 16
c mttc.algo.fy.run_random_walk 16
o mttc.algo.fy.run_random_walk 18
c mttc.algo.fy.run_random_walk 18
o mttc.algo.fy.run_random_walk 20
c mttc.algo.fy.run_random_walk 20
o mttc.algo.fy.run_random_walk 22
c mttc.algo.fy.run_random_walk 22
o mttc.algo.fy.run_random_walk 25
o mttc.algo.fy.run_random_walk 42
c mttc.algo.fy.run_random_walk 42
c mttc.algo.fy.run_random_walk 25
o mttc.algo.fy.run_random_walk 49
c mttc.algo.fy.run_random_walk 49
c mttc.algo.fy.run_random_walk 12
o mttc.algo.fy.run_algo 17
c mttc.algo.fy.run_algo 17
o mttc.algo.fy.run_algo 20
c mttc.algo.fy.run_algo 20
o mttc.algo.fy.run_algo 22
c mttc.algo.fy.run_algo 22
o mttc.algo.fy.run_algo 24
c mttc.algo.fy.run_algo 24
o mttc.algo.fy.run_algo 25
c mttc.algo.fy.run_algo 25
o mttc.algo.fy.run_algo 27
c mttc.algo.fy.run_algo 27
o mttc.algo.fy.run_algo 28
c mttc.algo.fy.run_algo 28
o mttc.algo.fy.run_algo 30
c mttc.algo.fy.run_algo 30
o mttc.algo.fy.run_algo 32
c mttc.algo.fy.run_algo 32
o mttc.algo.fy.run_algo 34
c mttc.algo.fy.run_algo 34
o mttc.algo.fy.run_algo 35
c mttc.algo.fy.run_algo 35
o mttc.algo.fy.run_algo 36
c mttc.algo.fy.run_algo 36
o mttc.algo.fy.run_algo 38
c mttc.algo.fy.run_algo 38
o mttc.algo.fy.run_algo 39
c mttc.algo.fy.run_algo 39
o mttc.algo.fy.run_algo 41
c mttc.algo.fy.run_algo 41
o mttc.algo.fy.run_algo 43
c mttc.algo.fy.run_algo 43
o mttc.algo.fy.run_algo 44
c mttc.algo.fy.run_algo 44
o mttc.algo.fy.run_algo 45
c mttc.algo.fy.run_algo 45
o mttc.algo.fy.run_algo 47
c mttc.algo.fy.run_algo 47
o mttc.algo.fy.run_algo 48
c mttc.algo.fy.run_algo 48
o mttc.algo.fy.run_algo 50
c mttc.algo.fy.run_algo 50
o mttc.algo.fy.run_algo 51
c mttc.algo.fy.run_algo 51
o mttc.algo.fy.run_algo 53
c mttc.algo.fy.run_algo 53
o mttc.vopp.rw.fy.option_init 6
c mttc.vopp.rw.fy.option_init 6
o mttc.vopp.rw.fy.option_init 7
c mttc.vopp.rw.fy.option_init 7
o mttc.vopp.rw.fy.option_init 8
c mttc.vopp.rw.fy.option_init 8
o mttc.vopp.rw.fy.option_init 11
c mttc.vopp.rw.fy.option_init 11
o mttc.vopp.rw.fy.option_init 13
c mttc.vopp.rw.fy.option_init 13
o mttc.vopp.rw.fy.option_init 14
c mttc.vopp.rw.fy.option_init 14
o mttc.vopp.rw.fy.option_init 18
c mttc.vopp.rw.fy.option_init 18
o mttc.vopp.rw.fy.option_init 21
o mttc.vopp.rw.fy.option_init 22
c mttc.vopp.rw.fy.option_init 22
c mttc.vopp.rw.fy.option_init 21
o mttc.vopp.rw.fy.option_init 24
o mttc.vopp.rw.fy.option_init 25
c mttc.vopp.rw.fy.option_init 25
c mttc.vopp.rw.fy.option_init 24
o mttc.vopp.rw.fy.value 10
c mttc.vopp.rw.fy.value 10
o mttc.vopp.rw.fy.value 12
c mttc.vopp.rw.fy.value 12
"""

s = s.splitlines()[1:]
o = {}
c = {}

print('not open\n')
for line in s:
	mark, dotted, line = line.split(' ')
	tag = dotted + ':' + line
	if mark == 'o':
		o[tag] = ''

	else:
		if tag not in o:
			print('', tag)
		else:
			del o[tag]

print('\nnot closed\n')
for k in o:
	print('', k)
