<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>fy</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*(def|type|interface)\s+([.a-zA-Z0-9_ &lt;]+)\s*(\((.*)\))?\s*:|\{\s*$|\(\s*$|\[\s*$|^\s*"""(?=.)(?!.*""")</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*\}|^\s*\]|^\s*\)|^\s*"""\s*$</string>
	<key>name</key>
	<string>fython</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?i)\#\#</string>
			<key>end</key>
			<string>(?i)\#\#</string>
			<key>name</key>
			<string>comment.block.fython</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)\'\'\'</string>
			<key>end</key>
			<string>(?i)\'\'\'</string>
			<key>name</key>
			<string>string.block.fython</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?i)\"\"\"</string>
			<key>end</key>
			<string>(?i)\"\"\"</string>
			<key>name</key>
			<string>string.block.fython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\#.*</string>
			<key>name</key>
			<string>comment.line.number-sign.fython</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.function.fython</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.fython</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(?i)\b(def|class)\s.*?\s?(\w+)(\s*\:)</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b\d+\.\d*([de][+-]?\d+)?\b</string>
			<key>name</key>
			<string>constant.numeric.fython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)(true|false)</string>
			<key>name</key>
			<string>constant.language.fython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(inline|interface|import|print|xip|read|result|arg|res|bind|iso|in|out|inout|sub)\b</string>
			<key>name</key>
			<string>keyword.other.fython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(if|then|else|elif|while|where|for|continue|break|pass|return)\b</string>
			<key>name</key>
			<string>keyword.control.fython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)[\s](and|or|not)[\s]</string>
			<key>name</key>
			<string>keyword.operator.logical.fython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\=|&gt;|&lt;|\!\=|\+|\-|\*|\/|</string>
			<key>name</key>
			<string>keyword.operator.fython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\"([^"]*)\"</string>
			<key>name</key>
			<string>string.quoted.single.fython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\'([^']*)\'</string>
			<key>name</key>
			<string>string.quoted.single.fython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(present|size|nullify|open|close|inquire|lbound|ubound|sin|cos|asin|acos|tan|atan)(?=\s*\()</string>
			<key>name</key>
			<string>support.function.fython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(selected_real_kind|allocated|shape)(?=\s*\()</string>
			<key>name</key>
			<string>support.function.fython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)[\s]\b(sum|product|count|matmul|ceiling|max|min|maxval|minval|maxloc|minloc)(?=\s*\()</string>
			<key>name</key>
			<string>support.function.fython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(d?(sqrt|abs|erf|log|exp))(?=\s*\()</string>
			<key>name</key>
			<string>support.function.fython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(trim|adjustl|dot_product|all|any|reshape|transpose)(?=\s*\()</string>
			<key>name</key>
			<string>support.function.fython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\s\b(cons|spec|iso|recursive|pure|elemental|bind|iso|abstract|allocatable|dimension|pointer|target|intent|parameter)\b</string>
			<key>name</key>
			<string>storage.modifier.fython</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i)\b(int|char|bool|integer|real|complex|logical|character)\b</string>
			<key>name</key>
			<string>storage.type.fython</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.fython</string>
	<key>uuid</key>
	<string>4c3e44cc-30bd-4f10-8d69-304741d0e2d7</string>
</dict>
</plist>
