
# mark_newlinex_parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '6EA1F4ECE8EA7AFC6111FE53680DD060'
    
_lr_action_items = {'eofx':([1,2,3,5,6,8,10,11,14,16,],[5,-1,-6,-7,-4,-2,-3,-5,-10,-13,]),'lket':([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,],[7,-1,-6,7,-7,-4,-11,-2,-8,-3,-5,7,-9,-10,-12,-13,]),'lpar':([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,],[9,-1,-6,9,-7,-4,-11,-2,-8,-3,-5,9,-9,-10,-12,-13,]),'code':([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,],[10,-1,-6,10,-7,-4,-11,-2,-8,-3,-5,10,-9,-10,-12,-13,]),'rpar':([3,4,6,9,10,11,13,14,16,],[-6,14,-4,-8,-3,-5,-9,-10,-13,]),'bofx':([0,],[2,]),'$end':([1,2,3,5,6,8,10,11,14,16,],[0,-1,-6,-7,-4,-2,-3,-5,-10,-13,]),'rket':([3,6,7,10,11,12,14,15,16,],[-6,-4,-11,-3,-5,16,-10,-12,-13,]),'newline':([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,],[6,-1,-6,6,-7,-4,-11,-2,-8,-3,-5,6,-9,-10,-12,-13,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'ket':([1,4,12,],[3,3,3,]),'source':([0,],[1,]),'element':([1,4,12,],[8,13,15,]),'par':([1,4,12,],[11,11,11,]),'parR':([1,4,12,],[4,4,4,]),'ketR':([1,4,12,],[12,12,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> source","S'",1,None,None,None),
  ('source -> bofx','source',1,'p_bofx','mark_newlinex.py',134),
  ('source -> source element','source',2,'p_source','mark_newlinex.py',140),
  ('element -> code','element',1,'p_source_unary','mark_newlinex.py',146),
  ('element -> newline','element',1,'p_source_unary','mark_newlinex.py',147),
  ('element -> par','element',1,'p_source_unary','mark_newlinex.py',148),
  ('element -> ket','element',1,'p_source_unary','mark_newlinex.py',149),
  ('source -> source eofx','source',2,'p_eofx','mark_newlinex.py',155),
  ('parR -> lpar','parR',1,'p_parR','mark_newlinex.py',162),
  ('parR -> parR element','parR',2,'p_par_cont','mark_newlinex.py',168),
  ('par -> parR rpar','par',2,'p_par','mark_newlinex.py',174),
  ('ketR -> lket','ketR',1,'p_ketR','mark_newlinex.py',180),
  ('ketR -> ketR element','ketR',2,'p_ket_cont','mark_newlinex.py',186),
  ('ket -> ketR rket','ket',2,'p_ket','mark_newlinex.py',192),
]
